AllCops:
  NewCops: enable
  Exclude:
#    - db/schema.rb
Layout/LineLength:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

