# frozen_string_literal: true
require 'rspec/core/rake_task'

rspec = RSpec::Core::RakeTask.new(:spec)

require 'rubocop/rake_task'

RuboCop::RakeTask.new

#task default: %i[spec rubocop]

task default: :rspec

require 'yard'

YARD::Rake::YardocTask.new do |t|
  t.files   = ['lib/**/*.rb', 'src/**/*.rb']   # optional
  t.options = ['--any', '--extra', '--opts'] # optional
  t.stats_options = ['--list-undoc']         # optional
end


# To RuboCop the current commit -
# git diff-tree --no-commit-id --name-only -r HEAD --diff-filter AMT | xargs bundle exec rubocop
# To RuboCop the working tree changes -
# git diff --name-only --diff-filter AMT | xargs bundle exec rubocop
# To RuboCop all of the changes from the branch -
# git diff --name-only master --diff-filter AMT | xargs bundle exec rubocop
