services:
  registry_explorer:
    image: ${REGISTRY_HOST}/registry-explorer
    build:
      context: ../src_registry_explorer
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=src_registry_explorer
      cache_to:
        - type=gha,scope=src_registry_explorer,mode=max
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - 7000:7000
    environment:
      OTEL_LOG_LEVEL: debug
      OTEL_TRACES_EXPORTER: console,otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel.next/
