version: '3.8'
services:
  registry:
    image: registry:2.8.3
    container_name: my_registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - ../temp:/var/lib/registry
#      - ./data:/var/lib/registry
    restart: always